/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:49abc0d6-caec-4d80-b176-c0fb2dbef50b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Q0ukyAmCD",
    "aws_user_pools_web_client_id": "54tqt471sm7603cpmi0koecv11",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pagm5rr44fa5bdvx4y5duk7vjq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
